image: docker:latest

variables:
  REGISTRY: registry.bihealth.org
  CONTAINER_IMAGE: ${REGISTRY}/vre/service_provenance:${CI_COMMIT_SHORT_SHA}
  TARGET_RELEASE: provenance

build:
  stage: build
  tags:
    - VRE-Deployment
  script:
    - docker login ${REGISTRY} -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
    - docker build --build-arg PIP_USERNAME=${DOCKER_USER} --build-arg PIP_PASSWORD=${DOCKER_PASSWORD} --build-arg http_proxy=http://proxy.charite.de:8080/ --build-arg https_proxy=http://proxy.charite.de:8080/ -t ${CONTAINER_IMAGE} .
    - docker push ${CONTAINER_IMAGE}

deploy:
  stage: deploy
  tags:
    - VRE-Deployment
  script:
    - pwd
    - cd .. && ls
    - rm -rf vre-infra
    - git clone https://${DOCKER_USER}:${DOCKER_PASSWORD}@git.bihealth.org/vre/vre-infra.git
    - sed -r -i -e "s/(^${TARGET_RELEASE}_app_version\s*=\s*).*/\1\"${CI_COMMIT_SHORT_SHA}\"/" vre-infra/terraform/config/charite/charite.tfvars
    - cat vre-infra/terraform/config/charite/charite.tfvars|grep -i ^${TARGET_RELEASE}_app_version
    - cd vre-infra
    - 'git config user.name ${DOCKER_USERNAME} && git config user.email "indoc-devops@indocresearch.org"'
    - 'git config --global user.password ${DOCKER_PASSWORD}'
    - git diff
    - git stage terraform/config/charite/charite.tfvars
    - git status
    - git pull https://${DOCKER_USER}:${DOCKER_PASSWORD}@git.bihealth.org/vre/vre-infra.git HEAD:refs/heads/main
    - 'git commit  -m "[ci skip] Terraform Deployment: ${TARGET_RELEASE} to ${CI_COMMIT_SHORT_SHA} "'
    - git push https://${DOCKER_USER}:${DOCKER_PASSWORD}@git.bihealth.org/vre/vre-infra.git HEAD:refs/heads/main
