image: docker:latest

variables:
  REGISTRY: s-hdp-vre-v007.charite.de
  CONTAINER_IMAGE: ${REGISTRY}/provenance:${CI_COMMIT_SHORT_SHA}

build:
  stage: build
  tags:
    - VRE-Deployment
  script:
    - docker login ${REGISTRY} -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
    - docker build --build-arg http_proxy=http://proxy.charite.de:8080/ --build-arg https_proxy=http://proxy.charite.de:8080/ -t ${CONTAINER_IMAGE} .
    - docker push ${CONTAINER_IMAGE}

deploy:
  stage: deploy
  tags:
    - VRE-Deployment
  script:
    - sed -i "s/<VERSION>/${CI_COMMIT_SHORT_SHA}/g" kubernetes/deployment.yaml
    - kubectl apply -f kubernetes/deployment.yaml
