GET_LINEAGE = {   'code': 200,
    'error_msg': '',
    'num_of_pages': 1,
    'page': 0,
    'result': {   'baseEntityGuid': '00353fbd-6ade-4c64-ae9a-e2f803906955',
                  'guidEntityMap': {   '00353fbd-6ade-4c64-ae9a-e2f803906955': {   'attributes': {   'createTime': 1612211682,
                                                                                                     'description': 'processed '
                                                                                                                    'by '
                                                                                                                    'data_transfer',
                                                                                                     'full_path': '/data/vre-storage/TRASH/0201/test_计划通59_1612211721.png',
                                                                                                     'global_entity_id': 'file_data-098c2d14-64cd-11eb-81f3-be498ca98c54-1612211735',
                                                                                                     'name': '/data/vre-storage/TRASH/0201/test_计划通59_1612211721.png',
                                                                                                     'owner': 'admin',
                                                                                                     'qualifiedName': '/data/vre-storage/TRASH/0201/test_计划通59_1612211721.png'},
                                                                                   'classificationNames': [   ],
                                                                                   'displayText': '/data/vre-storage/TRASH/0201/test_计划通59_1612211721.png',
                                                                                   'guid': '00353fbd-6ade-4c64-ae9a-e2f803906955',
                                                                                   'isIncomplete': False,
                                                                                   'labels': [   ],
                                                                                   'meaningNames': [   ],
                                                                                   'meanings': [   ],
                                                                                   'status': 'ACTIVE',
                                                                                   'typeName': 'file_data'},
                                       '36b7a1d0-9a35-4708-b2df-e11382497027': {   'attributes': {   'description': 'data_transfer '
                                                                                                                    'Processed',
                                                                                                     'name': '0201:data_transfer:1612211680.723016:test_计划通59.png:to:test_计划通59.png:v2',
                                                                                                     'qualifiedName': '0201:data_transfer:1612211680.723016:test_计划通59.png:to:test_计划通59.png:v2'},
                                                                                   'classificationNames': [   ],
                                                                                   'displayText': '0201:data_transfer:1612211680.723016:test_计划通59.png:to:test_计划通59.png:v2',
                                                                                   'guid': '36b7a1d0-9a35-4708-b2df-e11382497027',
                                                                                   'isIncomplete': False,
                                                                                   'labels': [   ],
                                                                                   'meaningNames': [   ],
                                                                                   'meanings': [   ],
                                                                                   'status': 'ACTIVE',
                                                                                   'typeName': 'Process'},
                                       '90dba9af-1ad7-40ba-9c6f-b6d37a7b83f1': {   'attributes': {   'description': 'data_delete '
                                                                                                                    'Processed',
                                                                                                     'name': '0201:data_delete:1612211735.593308:test_计划通59_1612211736.png:to:test_计划通59_1612211721.png:v2',
                                                                                                     'qualifiedName': '0201:data_delete:1612211735.593308:test_计划通59_1612211736.png:to:test_计划通59_1612211721.png:v2'},
                                                                                   'classificationNames': [   ],
                                                                                   'displayText': '0201:data_delete:1612211735.593308:test_计划通59_1612211736.png:to:test_计划通59_1612211721.png:v2',
                                                                                   'guid': '90dba9af-1ad7-40ba-9c6f-b6d37a7b83f1',
                                                                                   'isIncomplete': False,
                                                                                   'labels': [   ],
                                                                                   'meaningNames': [   ],
                                                                                   'meanings': [   ],
                                                                                   'status': 'ACTIVE',
                                                                                   'typeName': 'Process'},
                                       '9a141128-5278-4646-b10f-48d50f86968a': {   'attributes': {   'createTime': 1612211682,
                                                                                                     'description': 'processed '
                                                                                                                    'by '
                                                                                                                    'data_transfer',
                                                                                                     'full_path': '/data/vre-storage/0201/processed/straight_copy/test_计划通59_1612211736.png',
                                                                                                     'global_entity_id': 'file_data-e99cc36a-64cc-11eb-81f3-be498ca98c54-1612211682',
                                                                                                     'name': '/data/vre-storage/0201/processed/straight_copy/test_计划通59_1612211736.png',
                                                                                                     'owner': 'admin',
                                                                                                     'qualifiedName': '/data/vre-storage/0201/processed/straight_copy/test_计划通59_1612211736.png'},
                                                                                   'classificationNames': [   ],
                                                                                   'displayText': '/data/vre-storage/0201/processed/straight_copy/test_计划通59_1612211736.png',
                                                                                   'guid': '9a141128-5278-4646-b10f-48d50f86968a',
                                                                                   'isIncomplete': False,
                                                                                   'labels': [   ],
                                                                                   'meaningNames': [   ],
                                                                                   'meanings': [   ],
                                                                                   'status': 'ACTIVE',
                                                                                   'typeName': 'file_data'},
                                       'af98ee52-373e-4a12-be92-480c26d85495': {   'attributes': {   'createTime': 1612211654,
                                                                                                     'description': 'Raw '
                                                                                                                    'file '
                                                                                                                    'in '
                                                                                                                    'greenroom',
                                                                                                     'full_path': '/data/vre-storage/0201/raw/test_计划通59.png',
                                                                                                     'global_entity_id': 'file_data-d952e688-64cc-11eb-966c-be498ca98c54-1612211654',
                                                                                                     'name': '/data/vre-storage/0201/raw/test_计划通59.png',
                                                                                                     'owner': 'admin',
                                                                                                     'qualifiedName': '/data/vre-storage/0201/raw/test_计划通59.png'},
                                                                                   'classificationNames': [   ],
                                                                                   'displayText': '/data/vre-storage/0201/raw/test_计划通59.png',
                                                                                   'guid': 'af98ee52-373e-4a12-be92-480c26d85495',
                                                                                   'isIncomplete': False,
                                                                                   'labels': [   'asdas-dsa'],
                                                                                   'meaningNames': [   ],
                                                                                   'meanings': [   ],
                                                                                   'status': 'ACTIVE',
                                                                                   'typeName': 'file_data'}},
                  'lineageDepth': 50,
                  'lineageDirection': 'INPUT',
                  'relations': [   {   'fromEntityId': '9a141128-5278-4646-b10f-48d50f86968a',
                                       'relationshipId': '6f6a4085-bc09-4568-a776-b0f0f2b1c2a5',
                                       'toEntityId': '90dba9af-1ad7-40ba-9c6f-b6d37a7b83f1'},
                                   {   'fromEntityId': '90dba9af-1ad7-40ba-9c6f-b6d37a7b83f1',
                                       'relationshipId': '1efce6b8-c403-4855-aac8-81442e32cde8',
                                       'toEntityId': '00353fbd-6ade-4c64-ae9a-e2f803906955'},
                                   {   'fromEntityId': 'af98ee52-373e-4a12-be92-480c26d85495',
                                       'relationshipId': '9979b9e4-1468-4202-adb7-621cf347a77e',
                                       'toEntityId': '36b7a1d0-9a35-4708-b2df-e11382497027'},
                                   {   'fromEntityId': '36b7a1d0-9a35-4708-b2df-e11382497027',
                                       'relationshipId': '8066ca9d-4e69-4a0f-9b81-0624f96131fd',
                                       'toEntityId': '9a141128-5278-4646-b10f-48d50f86968a'}]},
    'total': 1}
